spring.application.name=bibliotecavirtual
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotecavirtual
spring.datasource.username=postgres
spring.datasource.password=mic@ws2909
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
